### PR TITLE
feat: homepage

### PR DESCRIPTION
**Pull request by ParthParolekar**
Added homepage for E-Commerce site.
live: https://deploy-preview-1--suspicious-rosalind-5520a4.netlify.app/

### CODE REVIEW

**Review by anik31 — APPROVED** [review]
Good work

**Review by ApurvaSawant11 — APPROVED** [review]
Looks good to me. Good color contrast. Just add some padding to the card badge. Also, it should be "50% off". Just "50%" doesn't convey meaning immediately.

**Comment by ParthParolekar** [comment]
> Looks good to me. Good color contrast. Just add some padding to the card badge. Also, it should be "50% off". Just "50%" doesn't convey meaning immediately.

Done! Thank you for the suggestion

**Comment by ParthParolekar** [comment]
Thank you @anik31 and @ApurvaSawant11 for the reviews. Merging now

**Pull request merged**
